### ISSUE TITLE
Error: Failed to launch chrome! spawn

### ISSUE THREAD

**Issue by kjr247** [crespowang/serverless-lambda-puppeteer#1]
Error: Failed to launch chrome! spawn ./node_modules/puomium/mac-674921/chrome-mac/Chromium.app/Contents/MacOS

running on windows 10. Is this expected to be on mac?

**Comment by kjr247** [comment]
Read the article. This was helpful.

> I can’t use the full version of puppeteer because the deployment package will go over AWS Lambda size limit, luckily with chrome-aws-lambda it ships an appropriate chromium binary for lambda nodejs environment. puppeteer-core is a version of Puppeteer that doesn’t download Chromium by default, so together with chrome-aws-lambda it provides a “full” puppeteer and is small enough to be deployed.
> It works fine in Lambda, but if you will have an error in your local dev run.
> Chromium revision is not downloaded. Run "npm install" or "yarn install"
> This is because as we just talked about, puppeteer-core doesn’t download chromium and chrome-aws-lambda is only for AWS lambda, ie not for your local environment, to make it work locally we need to install the full puppeteer as devDependencies, and in the code we need to check if the request comes from serverless-offline, if yes then set the executablePath to your local Chromium.

**Comment by kjr247** [comment]
Actually that wasn't the issue. I'd like to reopen.

**Comment by crespowang** [comment]
The local config `./node_modules/puomium/mac-674921/chrome-mac/Chromium.app/Contents/MacOS` is only for macos, you are running on Windows so I would find out your local path and replace it in the source code.

**Comment by kjr247** [comment]
That was absolutely the fix. In the pdf.ts. I wrote the code like.

```javascript
import puppeteer from "puppeteer";
import {
  cors,
  doNotWaitForEmptyEventLoop,
  httpHeaderNormalizer,
  httpErrorHandler
} from "middy/middlewares";

const handler = async (event: any) => {

  const browser = await puppeteer.launch({
    args: chromium.args
  });
```
